---
- name: config git enviroment, set user.email
  git_config:
    name: user.email
    scope: global
    value: 'root@{{ ansible_fqdn }}'

- name: config git enviroment, set user.name
  git_config:
    name: user.name
    scope: global
    value: '{{ ansible_fqdn }}'
    

- name: update repository
  git:
    dest: /data/d_coredns/gitRepo # required. The path of where the repository should be checked out. This parameter is required, unless C(clone) is set to C(no).
    repo: https://github.com/brtlvrs/demo.git # required. git, SSH, or HTTP(S) protocol address of the git repository.
    clone: yes 
    update: yes #key_file: /root/.ssh/photon-01_github
    accept_hostkey: yes
    remote: origin
    version: coredns-data
