---



- name: pull/update coreDNS-zones repository
  include_role: 
    name: git-coredns-zones
  register: gitResult
  when: updateGitRepos

- name: clear docker coredns container
  docker_container:
    name: coredns
    state: absent
  when: gitResult.changed or not updateGitRepos

- name: run coredns container
  docker_container:
    name: coredns # required. Assign a name to a new container or match an existing container.,When identifying an existing container name may be a name or a long or short container ID.
    image: coredns:latest # not required. Repository path and tag used to create the container. If an image is not found or pull is true, the image will be pulled from the registry. If no tag is included, 'latest' will be used.
    restart: no # not required. Use with started state to force a matching container to be stopped and restarted.
    debug: yes # not required. Debug mode
    recreate: yes
    domainname: shire.loc # not required. Container domainname.
    state: started # not required. choices: absent;present;stopped;started. I(absent) - A container matching the specified name will be stopped and removed. Use force_kill to kill the container rather than stopping it. Use keep_volumes to retain volumes associated with the removed container.,I(present) - Asserts the existence of a container matching the name and any provided configuration parameters. If no container matches the name, a container will be created. If a container matches the name but the provided configuration does not match, the container will be updated, if it can be. If it cannot be updated, it will be removed and re-created with the requested config. Image version will be taken into account when comparing configuration. To ignore image version use the ignore_image option. Use the recreate option to force the re-creation of the matching container. Use force_kill to kill the container rather than stopping it. Use keep_volumes to retain volumes associated with a removed container.,I(started) - Asserts there is a running container matching the name and any provided configuration. If no container matches the name, a container will be created and started. If a container matching the name is found but the configuration does not match, the container will be updated, if it can be. If it cannot be updated, it will be removed and a new container will be created with the requested configuration and started. Image version will be taken into account when comparing configuration. To ignore image version use the ignore_image option. Use recreate to always re-create a matching container, even if it is running. Use restart to force a matching container to be stopped and restarted. Use force_kill to kill a container rather than stopping it. Use keep_volumes to retain volumes associated with a removed container.,I(stopped) - Asserts that the container is first I(present), and then if the container is running moves it to a stopped state. Use force_kill to kill a container rather than stopping it.
    cleanup: yes # not required. Use with I(detach=false) to remove the container after successful execution.
    ports: 
      - "{{ansible_default_ipv4.address}}:53:53/udp" 
      - "{{ansible_default_ipv4.address}}:53:53/tcp"
    restart_policy: "no" # not required. choices: no;on-failure;always;unless-stopped. Container restart policy. Place quotes around I(no) option.
    command: "-conf /root/corefile" # not required. Command to execute when the container starts. A command may be either a string or a list. Prior to version 2.4, strings were split on commas.
    volumes: 
      - "/data/d_coredns/gitRepo/coreDNS/:/root/" # not required. List of volumes to mount within the container.,Use docker CLI-style syntax: C(/host:/container[:mode]),You can specify a read mode for the mount with either C(ro) or C(rw).,SELinux hosts can additionally use C(z) or C(Z) to use a shared or private label for the volume.
