---
- hosts: ctlNode
 # gather_facts: yes
  become: true

  pre_tasks:
  roles:
    - role: pre_task-copyKeys #-- copying ssh key file  to access photonOS VM with ansible

- hosts: photonNode
  gather_facts: yes
  become: true
  roles:
    - role: run-coredns #-- deploy coreDNS in docker
    - role: ansible-role-dns #-- configure name resolving to use coreDNS
      dns_domain: shire.loc
      dns_nameservers: ['{{ansible_default_ipv4.address}}', '8.8.8.8'] #-- use a second DNS server as backup for situations wheren coreDNS fails.
      dns_searchs: 'shire.loc'
  